heat_template_version: 2014-10-16

description: |
  Test template using Rackconnect. Parameter defaults should be valid for account
  rcheatdfwv3 in DFW.

  This template simply creates a server attached to a Rackconnect network in the
  region, attaches that server to an existing load balancer pool and assigns the
  server a Rackconnect public ip address.

parameters:

  rcnet:
    type: string
    description: The uuid of the Rackconnect network to use
    constraints:
    - custom_constraint: "rackconnect.network"
    default: "ec473e48-76f6-49bc-9cb2-9863399f9292"

  rcpool:
    type: string
    description: The uuid or name of the Rackconnect load balancer pool to use
    constraints:
    - custom_constraint: "rackconnect.pool"
    default: POOL_U_FOUND_IT

resources:

  # Attaches the server to the configured Rackconnect
  # load balancer pool
  pool_node:
    type: Rackspace::RackConnect::PoolNode
    properties:
      server_id: { get_resource: server }
      pool: { get_param: rcpool }


  # Attaches a Rackconnected public ip to the server
  public_ip:
    type: Rackspace::RackConnect::PublicIP
    properties:
      server_id: { get_resource: server }

  # Test with a Boot From Volume server
  bfv_pool_node:
     type: Rackspace::RackConnect::PoolNode
     properties:
       server_id: { get_resource: bfv_server }
       pool: { get_param: rcpool }


  # Attaches a Rackconnected public ip to the server
  bfv_public_ip:
     type: Rackspace::RackConnect::PublicIP
     properties:
       server_id: { get_resource: bfv_server }

  # Cloud server attached to a Rackconnect network
  server:
    type: OS::Nova::Server
    properties:
      image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      flavor: 2 GB Performance
      name:
        str_replace:
          template: stack-server
          params:
            stack: { get_param: "OS::stack_name" }
      networks:
      # Can only assign the server to a Rackconnect network
      # and optionally ServiceNet. Cannot assign to the
      # PublicNet (Note: Managed operations customers must
      # provide ServiceNet along with RackConnect network)
      - uuid: { get_param: rcnet }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

  # Boot from volume server.
  # Code contributed by: @ryan-walker
  bfv_server:
    type: OS::Nova::Server
    properties:
      block_device_mapping:
        - volume_id: {get_resource: volume}
          device_name: vda
          delete_on_termination: true
      user_data_format: RAW
      # config_drive: "true"
      flavor: 3.75 GB Compute v1
      name:
        str_replace:
          template: stack-server
          params:
            stack: { get_param: "OS::stack_name" }
      networks:
      # Can only assign the server to a Rackconnect network
      # and optionally ServiceNet. Cannot assign to the
      # PublicNet (Note: Managed operations customers must
      # provide ServiceNet along with RackConnect network)
      - uuid: { get_param: rcnet }
      - uuid: "11111111-1111-1111-1111-111111111111"
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

  volume:
    type: OS::Cinder::Volume
    properties:
      size: 50
      volume_type: SSD
      image: 749dc22a-9563-4628-b0d1-f84ced8c7b7a
