heat_template_version: 2014-10-16

description: |
  Test Rackspace::Cloud::Server and Fedora images

resources:

  fedora-21:
    type: Rackspace::Cloud::Server
    properties:
      image: Fedora 21 (PVHVM)
      flavor: 1 GB Performance
      name: 
        str_replace:
          template: stack-f21
          params:
            stack: { get_param: "OS::stack_name" }
      user_data:
        #!/bin/bash
        echo "Hello World" > test.txt
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

  fedora-22:
    type: Rackspace::Cloud::Server
    properties:
      image: Fedora 22 (PVHVM)
      flavor: 1 GB Performance
      name:
        str_replace:
          template: stack-f22
          params:
            stack: { get_param: "OS::stack_name" }
      user_data:
        #!/bin/bash
        echo "Hello World" > test.txt
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
  
  rhel-6:
    type: Rackspace::Cloud::Server
    properties:
      image: Red Hat Enterprise Linux 6 (PVHVM)
      flavor: 1 GB Performance
      name: 
        str_replace:
          template: stack-rhel-6
          params:
            stack: { get_param: "OS::stack_name" }
      user_data:
        #!/bin/bash
        echo "Hello World" > test.txt
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

  rhel-7:
    type: Rackspace::Cloud::Server
    properties:
      image: Red Hat Enterprise Linux 7 (PVHVM)
      flavor: 1 GB Performance
      name: 
        str_replace:
          template: stack-rhel-7
          params:
            stack: { get_param: "OS::stack_name" }
      user_data:
        #!/bin/bash
        echo "Hello World" > test.txt
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

  centos-6:
    type: Rackspace::Cloud::Server
    properties:
      image: CentOS 6 (PVHVM)
      flavor: 1 GB Performance
      name: 
        str_replace:
          template: stack-centos-6
          params:
            stack: { get_param: "OS::stack_name" }
      user_data:
        #!/bin/bash
        echo "Hello World" > test.txt
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

  centos-7:
    type: Rackspace::Cloud::Server
    properties:
      image: CentOS 7 (PVHVM)
      flavor: 1 GB Performance
      name: 
        str_replace:
          template: stack-centos-7
          params:
            stack: { get_param: "OS::stack_name" }
      user_data:
        #!/bin/bash
        echo "Hello World" > test.txt
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

outputs:

  fedora-21:
    value: { get_attr: [ fedora-21, accessIPv4 ] }

  rhel-6:
    value: { get_attr: [ rhel-6, accessIPv4 ] }

  rhel-7:
    value: { get_attr: [ rhel-7, accessIPv4 ] }

  centos-6:
    value: { get_attr: [ centos-6, accessIPv4 ] }

  centos-7:
    value: { get_attr: [ centos-7, accessIPv4 ] }

      


      
      
    
